[env]
AXUM_HTTP_REQUESTS_TOTAL = "product_service_requests_total"
AXUM_HTTP_REQUESTS_DURATION_SECONDS = "product_service_requests_duration_seconds"
AXUM_HTTP_REQUESTS_PENDING = "product_service_requests_pending"
AXUM_HTTP_RESPONSE_BODY_SIZE = "product_service_response_body_size"

[build]
rustflags = ["--cfg", "tracing_unstable"]